<?xml version ="1.0" encoding="UTF-8" ?>

<!DOCTYPE Noticias [
	<!ELEMENT Noticias (Noticia*) >
	<!ELEMENT Noticia (X, Y, Ancho, Alto, ColorTexto, TamanoTexto, Texto)>
	<!ELEMENT X (#PCDATA)>
	<!ELEMENT Y (#PCDATA)>
	<!ELEMENT Ancho (#PCDATA)>
	<!ELEMENT Alto (#PCDATA)>
	<!ELEMENT ColorTexto (#PCDATA)>
	<!ELEMENT TamanoTexto (#PCDATA)>
	<!ELEMENT Texto (#PCDATA)>
]>

<Noticias>
	<Noticia>
		<X>80px</X>
		<Y>112px</Y>
		<Ancho>250px</Ancho>
		<Alto>130px</Alto>
		<ColorTexto>#8822FF</ColorTexto>
		<TamanoTexto>100%</TamanoTexto>
		<Texto>Esta es la noticia 1</Texto>
	</Noticia>

	<Noticia>
		<X>250px</X>
		<Y>345px</Y>
		<Ancho>300px</Ancho>
		<Alto>80px</Alto>
		<ColorTexto>#EE00A0</ColorTexto>
		<TamanoTexto>160%</TamanoTexto>
		<Texto>Esta es la noticia 2</Texto>
	</Noticia>

 <Noticia>
   <X>400px</X>
   <Y>10px</Y>
   <Ancho>100px</Ancho>
   <Alto>100px</Alto>
   <ColorTexto></ColorTexto>
   <TamanoTexto>25px</TamanoTexto>
   <Texto>hola</Texto>
 </Noticia>

 <Noticia>
   <X>50px</X>
   <Y>50px</Y>
   <Ancho>50px</Ancho>
   <Alto>50px</Alto>
   <ColorTexto>#000000</ColorTexto>
   <TamanoTexto>20px</TamanoTexto>
   <Texto>sdfagag aga</Texto>
 </Noticia>
 

 <Noticia>
   <X>90px</X>
   <Y>90px</Y>
   <Ancho>90px</Ancho>
   <Alto>90px</Alto>
   <ColorTexto>#000000</ColorTexto>
   <TamanoTexto>20px</TamanoTexto>
   <Texto>gsh lgskj gs</Texto>
 </Noticia>
</Noticias>
